## Implementation using in-built modules

### importing the necessary libraries

In [41]:
import torch 
import torch.nn as nn 

- we getting 5 inputs passing it through sigmoid and getting 1 output

In [45]:
class Model(nn.Module): # inherit from nn.Module class
    
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1) # here num_features is the input and 1 is the output size
        self.sigmoid = nn.Sigmoid()
        
    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        
        return out

## Creating a fake dataset

In [46]:
features = torch.rand(10,5)

## creating model 
model = Model(features.shape[1])

## calling model
model(features) ## we are calling the forward function like this, automatically forward method is trigerred bt magic methods


tensor([[0.5239],
        [0.5023],
        [0.5705],
        [0.5691],
        [0.4992],
        [0.5533],
        [0.4991],
        [0.5195],
        [0.4725],
        [0.5159]], grad_fn=<SigmoidBackward0>)

In [48]:
#weights
model.linear.weight

Parameter containing:
tensor([[ 0.2359,  0.0740,  0.3049, -0.1390, -0.0568]], requires_grad=True)

In [49]:
# bias 
model.linear.bias

Parameter containing:
tensor([-0.1287], requires_grad=True)

## To view the summary of the neural network

In [51]:
! pip install torchinfo

In [54]:
from torchinfo import summary

summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Introducing a hidden layer

In [58]:
class Model(nn.Module):
    
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [59]:
features = torch.rand(10,5)

## creating model 
model = Model(features.shape[1])

## calling model
model(features) ## we are calling the forward function like this, automatically forward method is trigerred bt magic methods


tensor([[0.4933],
        [0.5024],
        [0.5152],
        [0.4522],
        [0.4860],
        [0.4857],
        [0.4781],
        [0.4922],
        [0.4640],
        [0.4760]], grad_fn=<SigmoidBackward0>)

In [60]:
summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Building model using sequential container

In [63]:
class Model(nn.Module):
    
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
           nn.Linear(num_features, 3),
           nn.ReLU(),
           nn.Linear(3,1),
           nn.Sigmoid()
        )
            
    def forward(self, features):
        out = self.network(features)
        return out

In [66]:
features = torch.rand(10,5)

## creating model 
model = Model(features.shape[1])

## calling model
model(features) ## we are calling the forward function like this, automatically forward method is trigerred bt magic methods


tensor([[0.5261],
        [0.5693],
        [0.5364],
        [0.5572],
        [0.5357],
        [0.5563],
        [0.5544],
        [0.5298],
        [0.5343],
        [0.5745]], grad_fn=<SigmoidBackward0>)

In [65]:
summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Using the breast cancer dataset

In [68]:
### importing the necessary libraries

In [69]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

### Loading the dataset

In [71]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [72]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

### Splitting the data

In [74]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Scaling the data

In [76]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Label encoding

In [78]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

### Converting numpy arrays to pytorch tensors

In [90]:
x_train_tensor = torch.from_numpy(X_train).float()
x_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()


### Building the model

In [91]:
class MySimpleNN(nn.Module):
    
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):

        out = self.linear(features)
        out = self.sigmoid(out)

        return out

In [92]:
learning_rate = 0.1
epochs = 25

### define loss function

In [93]:
loss_function = nn.BCELoss() ## Binary Cross entropy loss

### Training pipeline

- model.parameters() retrieves an iterator over all the trainable parameters (weights and biases) in a model.

In [94]:
# create model
model = MySimpleNN(x_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

    # forward pass
    y_pred = model(x_train_tensor)

    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1,1)) # .view is same as .reshape

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.8303563594818115
Epoch: 2, Loss: 0.6045196652412415
Epoch: 3, Loss: 0.4861657917499542
Epoch: 4, Loss: 0.4160914719104767
Epoch: 5, Loss: 0.3696209192276001
Epoch: 6, Loss: 0.33627206087112427
Epoch: 7, Loss: 0.3109528124332428
Epoch: 8, Loss: 0.2909129858016968
Epoch: 9, Loss: 0.27454236149787903
Epoch: 10, Loss: 0.2608364224433899
Epoch: 11, Loss: 0.24913528561592102
Epoch: 12, Loss: 0.23898684978485107
Epoch: 13, Loss: 0.23007015883922577
Epoch: 14, Loss: 0.22215060889720917
Epoch: 15, Loss: 0.2150522619485855
Epoch: 16, Loss: 0.20864014327526093
Epoch: 17, Loss: 0.20280896127223969
Epoch: 18, Loss: 0.19747494161128998
Epoch: 19, Loss: 0.19257056713104248
Epoch: 20, Loss: 0.18804077804088593
Epoch: 21, Loss: 0.18384002149105072
Epoch: 22, Loss: 0.1799301952123642
Epoch: 23, Loss: 0.17627927660942078
Epoch: 24, Loss: 0.1728600114583969
Epoch: 25, Loss: 0.16964904963970184


In [101]:
# model evaluation
with torch.no_grad():
    y_pred = model.forward(x_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5258541107177734
